### ISSUE TITLE
macOS LAPS Management Admin page view problems

### ISSUE THREAD

**Issue by unfo33** [munkireport/laps#11]
I believe the macOS LAPS management Admin view page is broken (at least on the quick demo setup). MunkiReportRunner appears to complete successfully and change the password if necessary but when I search for the serial on the Admin page it just does nothing (no error or anything). If I search for a non-existent serial it loads with default values and I noticed the random value I searched for is added to the database. If I try to search for that again (after its already in the DB) it doesn't load. Everything looks right in the Listings -> MacOSLAPS page. 
Also the "view all audits" button on the macOSLAPS page does nothing.

**Comment by joncrain** [comment]
Can you confirm which version of laps you're running and what version of MunkiReport? We have it running fine on laps v1.5 and the newest WIP branch.

**Comment by unfo33** [comment]
munkireport 5.4.1, and laps v1.5. I just tried to update to the latest WIP branch but it didn't seem to make a difference. I'm just on the quick demo setup on a single computer.

**Comment by tuxudo** [comment]
Download the latest master from GitHub. The latest version 1.5 is not up to date.

**Comment by unfo33** [comment]
So I just tried a fresh install of latest release of munkireport-php and downloaded the latest master of laps module to /vendor/munkireport/laps and get the same behavior. The first time I go to Admin->MacOSLAPS Management and put in my serial it shows default info. If I then try to search for that serial again no data is shown.

**Comment by tuxudo** [comment]
Contact me on the MacAdmins Slack, we can best work this out on there
