### ISSUE TITLE
Changes local admin password without warning if accidentally enabled

### ISSUE THREAD

**Issue by Tegenwind** [munkireport/laps#12]
On computers with an existing local admin account called 'admin', this mod will almost immediately and without warning change the password of this user, effectively locking you out when this is the only account with admin privileges.

On macOS 10.13 and lower this seems to happen almost instantaneously after installing the package, on 10.14 or higher it occurs after a longer period of time and sometimes seemingly not at all.

**Comment by tuxudo** [comment]
Working as designed. Most admin accounts on 10.14 and higher have a SecureToken. This module does not change the password if account has a SecureToken.

**Comment by bochoven** [comment]
I think adding a warning somewhere would help people that encounter this. Maybe in the documentation or somewhere in the setup.

**Comment by rickheil** [comment]
I think it would be wise to edit the username out entirely so that there is no accidental foot-gun.
