### ISSUE TITLE
audit column not created

### ISSUE THREAD

**Issue by joncrain** [munkireport/laps#2]
Trying to test the module and kept getting the following error:
```
Munkireport: Server An error occurred while processing: \Laps_model
Server Error: SQLSTATE[HY000]: General error: 1 table laps has no column named audit
Server info: starting: laps
```
I tried dropping the db and recreating, but still did not create the column. It's in the model, so I'm not sure what's going on. Manually creating the column allowed me to check a machine in.

**Comment by joncrain** [comment]
I'm wondering if it has to do with my missing Admin panel right now. Not sure if this is from my MR setup, or if I missed something in the config for the module.

**Comment by tuxudo** [comment]
There was a missing migration, added it. You may have to drop that column and run the migrations again. The admin page requires PR #1134 in MR core, it hasn't been merged in yet.
