### ISSUE TITLE
Type error 

### ISSUE THREAD

**Issue by guille-okt** [munkireport/laps#22]
This happens if we have value '' in audit column

 TypeError {#17
  #message: "count(): Argument #1 ($value) must be of type Countable|array, null given"
  #code: 0
  #file: "/custom_modules/munkireport/laps/laps_controller.php"
  #line: 309
  trace: {
    /custom_modules/munkireport/laps/laps_controller.php:309 {
      Laps_controller->save_audit_internal($action, $serial_number = '') …
      ›     $audit_new = array("timestamp"=>$timestamp,"username"=>$username,"remote_ip"=>$remote_ip,"user_agent"=>$user_agent,"action"=>$action);
      ›     $audit_out[count($audit_out)] = $audit_new;
      › }
    }

**Comment by guille-okt** [comment]
fixed by https://github.com/munkireport/laps/pull/23

**Comment by tuxudo** [comment]
Fixed in version v3.3 of the module. Thank you for the bug report and fix :D
